---
title: "Atelier du 16 mars 2023"
subtitle: "Utilisation de modèles de régression à coefficients variant dans le temps dans le cadre de la prévision conjoncturelle"
author: "Claire du Campe de Rosamel & Alain Quartier-la-Tente"
format: 
  revealjs:
   smaller: true
editor: visual
---

# Introduction

- contexte pourquoi on fait ça, des exemples d'applications (où ça peut être utile)

- expliquer le plan à travers un exemple

## Le modèle LM

- Exemple : modèle PIB

- A quoi ça ressemble un modèle LM

- hypothèses derrière l'estimation

- Montrer les résultats + graphiques sur les coefficients (estimation en temps-réel) ? Permet d'introduire les révisions et l'estimation en temps-réel ?


## Coefficients qui varient ???

Deux cas :

- hansen : décrire plus, ne pas forcément détailler toute la stat de test
  * Attention sur l'interprétation des résultats : si bouge pas d'après test peut quand même bouger.

- Décrire un peu plus Bai et Perron -> TODO ALAIN

  * Modèle
  * Comment sont déterminés les périodes ?
  * Implémentation en R
  * limites de Bai et perron (notamment dans l'implémentation : ensemble des variables) et attention sur l'interprétation des résultats.
  
- Si hansen bouge pas, bai et perron peut donner une date de rupture

## bplm et piecereg

- Parler de la différence entre bplm et piecereg et dire que nous on a retenu piecereg (on gagne des points et en pratique dire que c'est pareil car souvent dans les cas pratiques étudiés variance constante) en plus piecereg bien plus simples

- Exemple de code et résultat sur modèle PIB

## régressions locales : tvlm 

- détailler la théorie
- expliquer bw : estimation, bornes (20 = lm)

- détailler les sources des révisions : ajout d'un point, recalcul de bw (et donc nouvelle répartition des poids sur le passé)
- exemple modèle PIB, gif des coefs en focntion de bw

## espace état

- détailler la théorie : smoothing, filtering, analogie avec lm. 
- détailler var_ et fixed_ 
- exemple modèle PIB : un sans le package et un avec
- deux exemples de modèle PIB avec deux spécifications

## comparaison

- décrire ce qu'on a fait : modèles, période d'estimation
- résultats

## Modèles linéaires

$$
y_t=\beta_{0,t}+\beta_{1,t} x_{1,t}+\dots+\beta_{p,t}x_p +\varepsilon_t =
\beta_tX_t+\varepsilon_t
$$

Cas usuel de la régression linéaire : $\beta_t = \beta$

. . .

Hypothèse généralement fausse sur longue période ou lors de présence de changements structurels (changement de nomenclature, de définition, COVID...)

. . .

## Test de Hansen

Les tests classiques (type test de Chow, ou Bai Perron) supposent qu'il existe une date de rupture brutale, connue ou non. Or l'objectif premier est d'abord de savoir si un modèle est stable au cours du temps, si ses coefficients associés varient.

Tests trouvés dans la littérature autour de Nyblom et Hansen

Implémentation de ce test de Hansen (1992) dans le package : `hansen.test`

## Régression par morceau

Modèles les plus simples :

$$
\exists t_1,\dots,t_{T-1}:\:
\beta_t = \beta_1\mathbb 1_{t< t_1} + \beta_2 \mathbb 1_{t_1 \leq t< t_2} + \dots + \beta_T \mathbb 1_{t_{T-1} \leq t}
$$

. . .

S'estiment soit en découpant les variables explicatives ou en faisant des régressions linéaires par morceaux ($\mathbb V[\varepsilon_t]$ peut varier en fonction des périodes). Les deux options ont été testées, en terme de prévision quasiment identique. Différence de variance non testée/étudiée.

. . .

Bai et Perron (2003) : proposition d'algorithme efficace pour trouver les dates de ruptures. Mais la rupture peut être sur un sous-ensemble des variables, option non implémenté sous R (`strucchange`). L'algorithme de Bai et Perron ne teste que l'ensemble d'un modèle.

. . .

::: columns
::: {.column width="50%"}
Avantages :

::: incremental
-   Simples à comprendre, implémenter, s'appuie sur une régression linéaire classique
:::
:::

::: {.column width="50%"}
Inconvénients :

::: incremental
-   Suppose une rupture brutale
-   Imprécisions dans le choix de la date
:::
:::
:::

------------------------------------------------------------------------

Possibilité de fixer certaines variables, considérées comme non variantes (lors du test d'Hansen). Celles ci ne sont pas coupées en plusieurs sous-variables (calcul d'un seul coefficient).

Egalement poossible d'indiquer directement une, ou plusieurs, dates de rupture, dans le cas où elles seraient déjà connues. 

## Régressions locales

Package `tvreg`

Hypothèse $\beta_t = \beta(z_t)$ avec par défaut $z_t = t/T$

On suppose $\beta()$ localement constante (Nadaraya-Watson) ou localement linéaire .

. . .

Estimation : $$
\beta(z_t) = \underset{\theta_0}{\argmin}\sum_{j=1}^T\left(y_{j}-x_j\theta_0\right)^2K_b(z_j-z_t)
$$ Avec $K_b(x)=\frac 1 b K(x/b)$ fonction de noyau pour pondérer les observations

. . . 

Rmq : si $b\geq1$ on utilise toutes les données pour chaque estimation.

. . .

Problème du choix de $b$ : par validation croisée mais peu discriminant

. . .

Est-ce que l'on devrait également faire varier $b$ ? (notamment COVID)\
Tests de combinaison de Bai et Perron et régression locale encourageants

. . .

Inconvénient : toutes les coefficients varient

